run:
	@go run ./cmd/main.go

test:
	@go test -v ./...

test-cover:
	@go test ./... -coverprofile test-coverage.txt && go tool cover -html=test-coverage.txt

fix:
	@go fix ./...

fix-check:
	@go fix -diff ./...
